Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/02/2022
Var
x:inteiro
dia:caractere

Inicio
escreval("qual dia da semana vai cair o dia:")

leia(x)

ESCOLHA X

CASO 1
DIA<-"DOMINGO"
CASO 2
DIA<-"SEGUNDA"
CASO 3
DIA<-"TERÇA"
OUTROCASO
DIA<-"DIA NÃO CADASTRADO"
FIMESCOLHA

ESCREVA("o dia da semana é:",dia)

Fimalgoritmo