Algoritmo "MÉDIA DE CONSUMO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/01/2022
Var
// Seção de Declarações das variáveis 
DISTANCIA:REAL
COMBUSTIVEL:REAL
CONSUMO:REAL

Inicio
ESCREVAL("QUAL A DISTÂNCIA PERCORRIDA?")
LEIA(DISTANCIA)
ESCREVAL("QUANTO COMBUSTÍVEL FOI GASTO?")
LEIA(COMBUSTIVEL)
CONSUMO<-DISTANCIA/COMBUSTIVEL
ESCREVA("O CONSUMO MÉDIO POR LITRO É = ",CONSUMO:2:3)

Fimalgoritmo