Algoritmo "Terreno"
//  
//  

Var
largura:real
comprimento:real
area:real
metroQuadrado:real
preco:real

Inicio
escreval("Digite a largura do terreno: ")
leia(largura)
escreval("Digite o comprimento do terreno: ")
leia(comprimento)
escreval(" Digite o valor do metro quadrado do terreno: ")
leia(metroQuadrado)
escreval(" Area do terreno: ")
escreval(largura*comprimento)
area<- largura*comprimento
preco<-(area*metroQuadrado)
escreval("valor do terreno é de:")
escreval (preco)



Fimalgoritmo