Algoritmo "troco"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/01/2022
Var
 produto:real
 quantidade:inteiro
 dinheiro:real
 troco:real


Inicio
escreval("DIGITE O VALOR DO PRODUTO: ")
LEIA(PRODUTO)
ESCREVAL("QUANTIDADE: ")
LEIA(QUANTIDADE)
ESCREVAL("VALOR RECEBIDO DO CLIENTE:")
LEIA(DINHEIRO)
TROCO<-  DINHEIRO -(PRODUTO*QUANTIDADE)
ESCREVAL(" TROCO = ", TROCO)


Fimalgoritmo